baseURL = "https://hw.entsoc.io/"
languageCode = "en-us"
title = "Heriot-Watt EntSoc"

theme = "CAPSLOCK"

sectionPagesMenu = "main"
pygmentsOptions = "linenos=table"
pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true
buildFuture = true
summaryLength = 20

[params]
    description = "A group of people dedicated to small prototypes of big ideas."
    show_read_time = true
    service_worker = false
    show_contact_in_head = false
    show_contact_in_footer = true
    fontawesome_sets = ["light"]
    copyright = "all content on this site is free under the MIT license on [github](https://github.com/arlyon/entsoc)"
    foreground = "#000"
    background = "#FFF"

[[params.contact]]
    icon_type = "fal"
    icon_name = "at"
    link = "mailto:hw@entsoc.io"
    text = "contact"

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true