baseURL = "https://hach.arlyon.co/"
languageCode = "en-us"
title = "HackSock"

theme = "CAPSLOCK"

sectionPagesMenu = "main"
pygmentsOptions = "linenos=table"
pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
    description = "A group of people dedicated to small prototypes of big ideas."
    show_read_time = true
    service_worker = false
    show_contact_in_head = false
    show_contact_in_footer = true
    fontawesome_sets = ["brands"]
    copyright = "please vote"

    foreground = "#000"

[[params.contact]]
    icon_type = "fab"
    icon_name = "facebook"
    link = "https://www.facebook.com/hacksock"
    text = "FB"

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true