baseURL = "https://hach.arlyon.co/"
languageCode = "en-us"
title = "Heriot-Watt EntSoc"

theme = "CAPSLOCK"

sectionPagesMenu = "main"
pygmentsOptions = "linenos=table"
pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true
buildFuture = true

[params]
    description = "A group of people dedicated to small prototypes of big ideas."
    show_read_time = true
    service_worker = false
    show_contact_in_head = false
    show_contact_in_footer = true
    copyright = "all content on this site is free under the MIT license"

    foreground = "#00F"
    background = "#F00"

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true